default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  connect_timeout: 2
  checkout_timeout: 2
  host: localhost
  port: 5432
  username: polza_test
  password: polzatestovoe

development:
  <<: *default
  database: Polza_test_development

test:
  <<: *default
  database: Polza_test_test

production:
  <<: *default
